// AHK code generator — produces structured line objects for the preview pane
// and a flat string for the Rust apply_profile command.
// Supports both AHK v1 (Send, / Run, / return) and v2 (Send() / Run() / { }).

import type { Hotkey, Profile } from "../../lib/types";

export type AhkLine =
  | { k: "comment"; text: string }
  | { k: "hotkey"; text: string; comment?: string }
  | { k: "cmd"; text: string }
  | { k: "return"; text: string }
  | { k: "blank" };

export type AhkVersion = 1 | 2;

// ── Main entry point ────────────────────────────────────────────────
export function generateAhk(profile: Profile, version: AhkVersion = 1): AhkLine[] {
  const lines: AhkLine[] = [];

  lines.push({ k: "comment", text: `; Generated by AHK Manager — Profile: ${profile.name}` });
  lines.push({ k: "comment", text: `; Do not edit manually — use AHK Manager instead` });
  if (version === 2) {
    lines.push({ k: "comment", text: `; AutoHotkey v2 syntax` });
  }
  lines.push({ k: "blank" });
  // Prevents AHK from showing a "replace existing instance?" dialog when the
  // same temp file is relaunched (e.g. switching profiles).
  lines.push({ k: "cmd", text: "#SingleInstance Force" });
  lines.push({ k: "blank" });

  const active = profile.hotkeys.filter((h) => h.enabled);
  if (active.length === 0) {
    lines.push({ k: "comment", text: "; No enabled hotkeys" });
    return lines;
  }

  active.forEach((h, idx) => {
    if (idx > 0) lines.push({ k: "blank" });
    lines.push({ k: "hotkey", text: `${h.trigger}::`, comment: h.description || undefined });

    if (version === 1) {
      generateV1Body(h, lines);
    } else {
      generateV2Body(h, lines);
    }
  });

  return lines;
}

// ── AHK v1 body ─────────────────────────────────────────────────────
function generateV1Body(h: Hotkey, lines: AhkLine[]): void {
  switch (h.action_type) {
    case "send_text": {
      const v = escapeV1Text(h.action_value);
      lines.push({ k: "cmd", text: `    Send, ${v}` });
      if (h.append_enter) lines.push({ k: "cmd", text: `    Send, {Enter}` });
      break;
    }
    case "run":
      lines.push({ k: "cmd", text: `    Run, ${h.action_value}` });
      break;
    case "always_on_top":
      lines.push({ k: "cmd", text: `    Winset, Alwaysontop, , A` });
      break;
    case "custom":
      h.action_value.split("\n").forEach((l) => {
        lines.push({ k: "cmd", text: `    ${l}` });
      });
      break;
  }
  lines.push({ k: "return", text: "return" });
}

// ── AHK v2 body ─────────────────────────────────────────────────────
function generateV2Body(h: Hotkey, lines: AhkLine[]): void {
  lines.push({ k: "cmd", text: "{" });
  switch (h.action_type) {
    case "send_text": {
      const v = escapeV2Text(h.action_value);
      lines.push({ k: "cmd", text: `    Send("${v}")` });
      if (h.append_enter) lines.push({ k: "cmd", text: `    Send("{Enter}")` });
      break;
    }
    case "run":
      lines.push({ k: "cmd", text: `    Run("${escapeV2Run(h.action_value)}")` });
      break;
    case "always_on_top":
      lines.push({ k: "cmd", text: `    WinSetAlwaysOnTop(-1, "A")` });
      break;
    case "custom":
      // Upgrade any v1-style commands that were imported/stored before this fix.
      // Lines already in v2 syntax are passed through unchanged.
      h.action_value.split("\n").forEach((l) => {
        lines.push({ k: "cmd", text: `    ${upgradeV1LineToV2(l)}` });
      });
      break;
  }
  lines.push({ k: "cmd", text: "}" });
}

/**
 * Best-effort upgrade of a single AHK v1 command line to v2 syntax.
 * Only touches the most common commands; unknown lines are left as-is.
 */
function upgradeV1LineToV2(line: string): string {
  const t = line.trim();

  // Already v2 — has Send(...) / Run(...) style
  if (/^Send\s*\(/i.test(t) || /^Run\s*\(/i.test(t)) return line;

  // Send, value  →  Send("value")
  const sendM = t.match(/^Send,\s+(.+)$/i);
  if (sendM) return line.replace(t, `Send("${sendM[1]}")`);

  // Send value (no comma — AHK v1 also accepts this form)  →  Send("value")
  const sendNoCommaM = t.match(/^Send\s+(.+)$/i);
  if (sendNoCommaM) return line.replace(t, `Send("${sendNoCommaM[1]}")`);

  // Run, value  →  Run("value")
  const runM = t.match(/^Run,\s+(.+)$/i);
  if (runM) return line.replace(t, `Run("${runM[1]}")`);

  // Run value (no comma)  →  Run("value")
  const runNoCommaM = t.match(/^Run\s+(.+)$/i);
  if (runNoCommaM) return line.replace(t, `Run("${runNoCommaM[1]}")`);

  // Winset, Alwaysontop, ...  →  WinSetAlwaysOnTop(-1, "A")
  if (/^Winset,\s*Alwaysontop/i.test(t)) {
    return line.replace(t, `WinSetAlwaysOnTop(-1, "A")`);
  }

  // v1 `return` is not needed inside v2 { } blocks — drop it silently
  if (/^return$/i.test(t)) return "";

  return line;
}

// ── Escaping helpers ────────────────────────────────────────────────
function escapeV1Text(s: string): string {
  return s.replace(/\n/g, "`n").replace(/\t/g, "`t");
}

function escapeV2Text(s: string): string {
  return s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '`"')
    .replace(/\n/g, "`n")
    .replace(/\t/g, "`t");
}

function escapeV2Run(s: string): string {
  // Only escape backtick (AHK v2 escape char) and double quote (string delimiter).
  // Backslashes in paths are literal in AHK v2 strings — do not escape them.
  return s.replace(/`/g, "``").replace(/"/g, '`"');
}

// ── Flatten to plain string ─────────────────────────────────────────
export function flattenLines(lines: AhkLine[]): string {
  return lines
    .map((l) => {
      if (l.k === "blank") return "";
      if (l.k === "hotkey") {
        return l.comment ? `${l.text}  ; ${l.comment}` : l.text;
      }
      return l.text;
    })
    .join("\n");
}
