// app.jsx — AHK Manager main app
const { useState, useEffect, useRef, useMemo, useCallback } = React;

/* ── Seed data ───────────────────────────────────────────────────── */
const SEED_PROFILES = {
  "work-macros": {
    id: "work-macros",
    name: "Work Macros",
    hotkeys: [
      { id: "h1", trigger: "^+4", action_type: "send_text",
        action_value: "claude --dangerously-skip-permissions",
        append_enter: true, description: "Claude CLI command", enabled: true },
      { id: "h2", trigger: "^+1", action_type: "send_text",
        action_value: "user@company.com\tHunter2!",
        append_enter: false, description: "Login credentials", enabled: true },
      { id: "h3", trigger: "^SPACE", action_type: "always_on_top",
        action_value: "", append_enter: false,
        description: "Toggle always on top", enabled: true },
      { id: "h4", trigger: "^+T", action_type: "run",
        action_value: "wt.exe", append_enter: false,
        description: "Open Windows Terminal", enabled: true },
      { id: "h5", trigger: "!q", action_type: "send_text",
        action_value: "Best,\nAlex", append_enter: false,
        description: "Email signature", enabled: false },
      { id: "h6", trigger: "^+G", action_type: "custom",
        action_value: 'Run, https://github.com/notifications\nreturn',
        append_enter: false, description: "Open GitHub notifications", enabled: true },
    ],
  },
  "personal": {
    id: "personal",
    name: "Personal",
    hotkeys: [
      { id: "p1", trigger: "^!N", action_type: "run",
        action_value: "notepad.exe", append_enter: false,
        description: "Quick notes", enabled: true },
      { id: "p2", trigger: "#D", action_type: "send_text",
        action_value: "📅 Today's plan: ", append_enter: false,
        description: "Daily planner header", enabled: true },
    ],
  },
  "gaming": {
    id: "gaming",
    name: "Gaming",
    hotkeys: [
      { id: "g1", trigger: "F1", action_type: "send_text",
        action_value: "gg wp", append_enter: true,
        description: "Quick GG", enabled: true },
      { id: "g2", trigger: "F2", action_type: "send_text",
        action_value: "Nice play!", append_enter: true,
        description: "Compliment", enabled: true },
      { id: "g3", trigger: "F3", action_type: "send_text",
        action_value: "On my way", append_enter: true,
        description: "On the way", enabled: true },
    ],
  },
};

/* ── AHK Code generator ──────────────────────────────────────────── */
function generateAhk(profile) {
  const lines = [];
  lines.push({ k: "comment", text: `; Generated by AHK Manager — Profile: ${profile.name}` });
  lines.push({ k: "comment", text: "; Do not edit manually — use AHK Manager instead" });
  lines.push({ k: "blank" });
  const active = profile.hotkeys.filter((h) => h.enabled);
  if (active.length === 0) {
    lines.push({ k: "comment", text: "; No enabled hotkeys" });
    return lines;
  }
  active.forEach((h, idx) => {
    if (idx > 0) lines.push({ k: "blank" });
    lines.push({ k: "hotkey", text: `${h.trigger}::`, comment: h.description });
    if (h.action_type === "send_text") {
      const v = h.action_value.replace(/\n/g, "`n").replace(/\t/g, "`t");
      lines.push({ k: "cmd", text: `    Send, ${v}` });
      if (h.append_enter) lines.push({ k: "cmd", text: `    Send, {Enter}` });
    } else if (h.action_type === "run") {
      lines.push({ k: "cmd", text: `    Run, ${h.action_value}` });
    } else if (h.action_type === "always_on_top") {
      lines.push({ k: "cmd", text: `    Winset, Alwaysontop, , A` });
    } else if (h.action_type === "custom") {
      h.action_value.split("\n").forEach((l) => {
        lines.push({ k: "cmd", text: `    ${l}` });
      });
    }
    lines.push({ k: "return", text: "return" });
  });
  return lines;
}

/* ── Sidebar ─────────────────────────────────────────────────────── */
function Sidebar({ profiles, activeId, runningId, onSelect, onCreate, onDelete, onDuplicate, onApply, onStop }) {
  const ids = Object.keys(profiles);
  return (
    <div className="sidebar">
      <div className="sidebar-head">
        <span className="sidebar-head-title">Profiles</span>
        <span className="sidebar-head-count">{ids.length.toString().padStart(2, "0")}</span>
      </div>
      <div className="sidebar-list">
        {ids.map((id) => {
          const p = profiles[id];
          const active = id === activeId;
          const running = id === runningId;
          return (
            <div
              key={id}
              className={"profile-item " + (active ? "active " : "") + (running ? "running" : "")}
              onClick={() => onSelect(id)}
            >
              <span className="pi-dot" />
              <span className="pi-name">{p.name}</span>
              {!running && <span className="pi-count">{p.hotkeys.length}</span>}
              {running ? (
                <button
                  className="pi-action-btn stop-btn"
                  title="Stop this script (Ctrl+Enter)"
                  onClick={(e) => { e.stopPropagation(); onStop(); }}
                >
                  <Icon.Stop />
                </button>
              ) : (
                <span className="pi-actions">
                  <button className="pi-action-btn apply-btn" title="Apply this profile (Ctrl+Enter)"
                          onClick={(e) => { e.stopPropagation(); onSelect(id); onApply(id); }}>
                    <Icon.Play />
                  </button>
                  <button className="pi-action-btn" title="Duplicate"
                          onClick={(e) => { e.stopPropagation(); onDuplicate(id); }}>
                    <Icon.Copy />
                  </button>
                  <button className="pi-action-btn" title="Delete"
                          onClick={(e) => { e.stopPropagation(); onDelete(id); }}>
                    <Icon.Trash />
                  </button>
                </span>
              )}
            </div>
          );
        })}
      </div>
      <div className="sidebar-foot">
        <button className="btn ghost" style={{ width: "100%", justifyContent: "flex-start" }}
                onClick={onCreate}>
          <Icon.Plus />
          New Profile
        </button>
      </div>
    </div>
  );
}

/* ── Hotkey Table ────────────────────────────────────────────────── */
function HotkeyTable({ profile, query, onEdit, onDelete, onToggle, onAdd, onDuplicate }) {
  const filtered = useMemo(() => {
    if (!query) return profile.hotkeys;
    const q = query.toLowerCase();
    return profile.hotkeys.filter((h) =>
      h.trigger.toLowerCase().includes(q) ||
      h.description.toLowerCase().includes(q) ||
      (h.action_value || "").toLowerCase().includes(q)
    );
  }, [profile.hotkeys, query]);

  if (profile.hotkeys.length === 0) {
    return (
      <div className="empty">
        <div className="empty-mark"><Icon.Lightning /></div>
        <div className="empty-title">No hotkeys yet</div>
        <div className="empty-desc">
          Add a hotkey to bind a trigger (like <span className="mono">Ctrl+Shift+4</span>) to an
          action — send text, run a command, or write raw AHK.
        </div>
        <Button variant="primary" leftIcon={<Icon.Plus />} onClick={onAdd}>Add hotkey</Button>
      </div>
    );
  }

  if (filtered.length === 0) {
    return (
      <div className="empty">
        <div className="empty-mark"><Icon.Search /></div>
        <div className="empty-title">No matches</div>
        <div className="empty-desc">No hotkeys match "{query}". Try a different search term.</div>
      </div>
    );
  }

  return (
    <table className="table">
      <thead>
        <tr>
          <th className="col-toggle"></th>
          <th className="col-trigger">Trigger</th>
          <th className="col-action">Action</th>
          <th>Description</th>
          <th className="col-actions"></th>
        </tr>
      </thead>
      <tbody>
        {filtered.map((h) => (
          <tr key={h.id} className={h.enabled ? "" : "disabled"} onDoubleClick={() => onEdit(h)}>
            <td className="col-toggle">
              <Toggle on={h.enabled} onChange={() => onToggle(h.id)} />
            </td>
            <td className="col-trigger">
              <span className="drag-handle"><Icon.Drag /></span>
              <Keycap trigger={h.trigger} />
            </td>
            <td className="col-action">
              <ActionTag type={h.action_type} />
            </td>
            <td>
              <span className={"desc " + (h.description ? "" : "empty")}>
                {h.description || "No description"}
              </span>
              {h.action_type === "send_text" && h.action_value && (
                <div className="mono" style={{ fontSize: 11, color: "var(--text-3)", marginTop: 2,
                                                whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis", maxWidth: 360 }}>
                  → {h.action_value.replace(/\n/g, "↵").slice(0, 64)}
                </div>
              )}
            </td>
            <td className="col-actions">
              <div className="row-actions">
                <button className="btn ghost sm icon-only" title="Duplicate"
                        onClick={(e) => { e.stopPropagation(); onDuplicate(h.id); }}>
                  <Icon.Copy />
                </button>
                <button className="btn ghost sm icon-only" title="Edit"
                        onClick={(e) => { e.stopPropagation(); onEdit(h); }}>
                  <Icon.Edit />
                </button>
                <button className="btn ghost sm icon-only danger" title="Delete"
                        onClick={(e) => { e.stopPropagation(); onDelete(h.id); }}>
                  <Icon.Trash />
                </button>
              </div>
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

/* ── Hotkey Modal ────────────────────────────────────────────────── */
function HotkeyModal({ initial, onSave, onClose }) {
  const isEdit = !!initial.id;
  const [hk, setHk] = useState({
    id: initial.id || ("h" + Math.random().toString(36).slice(2, 8)),
    trigger: initial.trigger || "",
    action_type: initial.action_type || "send_text",
    action_value: initial.action_value || "",
    append_enter: !!initial.append_enter,
    description: initial.description || "",
    enabled: initial.enabled !== false,
  });
  const update = (k, v) => setHk((p) => ({ ...p, [k]: v }));

  const ACTIONS = [
    { key: "send_text", name: "Send Text", desc: "Type a string", tag: "send" },
    { key: "run", name: "Run Command", desc: "Launch a program", tag: "run" },
    { key: "always_on_top", name: "Always on Top", desc: "Pin active window", tag: "top" },
    { key: "custom", name: "Custom AHK", desc: "Raw AHK snippet", tag: "custom" },
  ];

  const canSave = hk.trigger.trim() &&
    (hk.action_type === "always_on_top" || hk.action_value.trim());

  return (
    <Modal onClose={onClose}>
      <div className="modal-head">
        <div className="modal-title">
          <span className="kicker">{isEdit ? "Edit" : "New"} Hotkey</span>
          <span style={{ color: "var(--text-2)" }}>
            {hk.trigger ? <Keycap trigger={hk.trigger} /> : "Untitled binding"}
          </span>
        </div>
        <button className="btn ghost sm icon-only" onClick={onClose}><Icon.Close /></button>
      </div>
      <div className="modal-body">
        <div className="input-group">
          <label>Trigger</label>
          <TriggerRecorder value={hk.trigger} onChange={(v) => update("trigger", v)} />
          <span className="hint">
            Modifiers: <span style={{ color: "var(--text-1)" }}>^</span> Ctrl ·{" "}
            <span style={{ color: "var(--text-1)" }}>+</span> Shift ·{" "}
            <span style={{ color: "var(--text-1)" }}>!</span> Alt ·{" "}
            <span style={{ color: "var(--text-1)" }}>#</span> Win
          </span>
        </div>

        <div className="input-group">
          <label>Action</label>
          <div className="action-grid">
            {ACTIONS.map((a) => (
              <button
                key={a.key}
                className={"action-card " + (hk.action_type === a.key ? "selected" : "")}
                onClick={() => update("action_type", a.key)}
              >
                <div className="ac-name">
                  <span className={"tag " + a.tag} style={{ padding: "1px 6px" }}>{a.name}</span>
                </div>
                <div className="ac-desc">{a.desc}</div>
              </button>
            ))}
          </div>
        </div>

        {hk.action_type === "send_text" && (
          <>
            <div className="input-group">
              <label>Text to send</label>
              <textarea
                className="textarea"
                placeholder="Hello, world!"
                value={hk.action_value}
                onChange={(e) => update("action_value", e.target.value)}
              />
              <span className="hint">Use \n for newline, \t for tab.</span>
            </div>
            <div className="flex gap-2" style={{ marginTop: -4 }}>
              <Toggle on={hk.append_enter} onChange={(v) => update("append_enter", v)} />
              <span style={{ fontSize: 12.5 }}>Press <Keycap trigger="Enter" /> after sending</span>
            </div>
          </>
        )}

        {hk.action_type === "run" && (
          <div className="input-group">
            <label>Command</label>
            <input
              className="input mono"
              placeholder="notepad.exe   or   C:\Tools\thing.bat"
              value={hk.action_value}
              onChange={(e) => update("action_value", e.target.value)}
            />
            <span className="hint">Path to an executable, batch file, or URL.</span>
          </div>
        )}

        {hk.action_type === "always_on_top" && (
          <div style={{ padding: 12, background: "var(--bg-1)", border: "1px solid var(--border)",
                        borderRadius: 6, fontSize: 12.5, color: "var(--text-1)", display: "flex", gap: 10, alignItems: "flex-start" }}>
            <Icon.Lightning />
            <div>Pressing this trigger will toggle "Always on Top" for the currently focused window. No additional configuration needed.</div>
          </div>
        )}

        {hk.action_type === "custom" && (
          <div className="input-group">
            <label>AHK code</label>
            <textarea
              className="textarea"
              placeholder={"Run, https://example.com\nreturn"}
              value={hk.action_value}
              onChange={(e) => update("action_value", e.target.value)}
              style={{ minHeight: 120 }}
            />
            <span className="hint">Will be inserted into the generated <span style={{ color: "var(--text-1)" }}>.ahk</span> file as-is.</span>
          </div>
        )}

        <div className="input-group">
          <label>Description <span style={{ textTransform: "none", letterSpacing: 0, color: "var(--text-3)" }}>(optional)</span></label>
          <input
            className="input"
            placeholder="A short note about what this hotkey does"
            value={hk.description}
            onChange={(e) => update("description", e.target.value)}
          />
        </div>
      </div>
      <div className="modal-foot">
        <div className="left">
          <Toggle on={hk.enabled} onChange={(v) => update("enabled", v)} />
          <span>{hk.enabled ? "Enabled" : "Disabled"}</span>
        </div>
        <div className="flex gap-2">
          <Button variant="ghost" onClick={onClose}>Cancel</Button>
          <Button variant="primary" disabled={!canSave} onClick={() => onSave(hk)}>
            {isEdit ? "Save changes" : "Add hotkey"}
          </Button>
        </div>
      </div>
    </Modal>
  );
}

/* ── Confirm Dialog ──────────────────────────────────────────────── */
function ConfirmDialog({ title, body, confirmLabel, onConfirm, onClose, danger }) {
  return (
    <Modal onClose={onClose} className="confirm">
      <div className="modal-body">
        <div className="confirm-icon" style={!danger ? { background: "var(--accent-soft)", color: "var(--accent)" } : undefined}>
          <Icon.Warn />
        </div>
        <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 4 }}>{title}</div>
        <div style={{ fontSize: 12.5, color: "var(--text-2)", textWrap: "pretty" }}>{body}</div>
      </div>
      <div className="modal-foot" style={{ justifyContent: "flex-end" }}>
        <Button variant="ghost" onClick={onClose}>Cancel</Button>
        <Button
          variant={danger ? "primary" : "primary"}
          style={danger ? { background: "var(--danger)", borderColor: "var(--danger)", boxShadow: "none" } : undefined}
          onClick={onConfirm}
        >{confirmLabel}</Button>
      </div>
    </Modal>
  );
}

/* ── Preview pane ────────────────────────────────────────────────── */
function PreviewPane({ profile, running, onCopy, onClose }) {
  const lines = useMemo(() => generateAhk(profile), [profile]);
  return (
    <div className="preview">
      <div className="preview-head">
        <div className={"preview-head-title " + (running ? "live" : "")}>
          <span className="dot" />
          <span>%TEMP%\ahk_manager_active.ahk</span>
          {running && <span style={{ color: "var(--success)" }}>· live</span>}
        </div>
        <div className="flex gap-2">
          <Button variant="ghost" size="sm" leftIcon={<Icon.Copy />} onClick={onCopy}>Copy</Button>
          <button className="btn ghost sm icon-only" onClick={onClose} title="Hide preview">
            <Icon.Close />
          </button>
        </div>
      </div>
      <div className="preview-body">
        {lines.map((l, i) => {
          if (l.k === "blank") return <div key={i} className="line"><span></span></div>;
          if (l.k === "comment") return <div key={i} className="line"><span className="ln-comment">{l.text}</span></div>;
          if (l.k === "hotkey") return (
            <div key={i} className="line">
              <span><span className="ln-hotkey">{l.text}</span>
                {l.comment && <span className="ln-comment">{"  ; " + l.comment}</span>}
              </span>
            </div>
          );
          if (l.k === "return") return <div key={i} className="line"><span className="ln-return">{l.text}</span></div>;
          return <div key={i} className="line"><span className="ln-cmd">{highlightCmd(l.text)}</span></div>;
        })}
      </div>
    </div>
  );
}

function highlightCmd(text) {
  // simple: highlight keyword (Send,/Run,/Winset, etc.) and strings
  const m = text.match(/^(\s*)(\w+)(,?\s*)(.*)$/);
  if (!m) return text;
  return (
    <>
      <span>{m[1]}</span>
      <span className="ln-kw">{m[2]}</span>
      <span>{m[3]}</span>
      <span>{m[4]}</span>
    </>
  );
}

Object.assign(window, {
  SEED_PROFILES, generateAhk, Sidebar, HotkeyTable, HotkeyModal, ConfirmDialog, PreviewPane,
});
