def _is_v2(exe_path: str) -> bool:
    return "v2" in exe_path.lower()


def generate(profile: dict, exe_path: str = "") -> str:
    name = profile.get("name", "Profile")
    v2 = _is_v2(exe_path)

    if v2:
        header = [
            f"; Generated by AHK Manager - Profile: {name}",
            "; Do not edit manually - use AHK Manager instead",
            "",
            "#SingleInstance",
            "",
        ]
    else:
        header = [
            f"; Generated by AHK Manager - Profile: {name}",
            "; Do not edit manually - use AHK Manager instead",
            "",
            "#NoEnv",
            "#SingleInstance Force",
            "SendMode Input",
            "",
        ]

    body = []
    for hk in profile.get("hotkeys", []):
        if not hk.get("enabled", True):
            continue

        trigger = hk["trigger"]
        action_type = hk["action_type"]
        value = hk.get("action_value", "")
        append_enter = hk.get("append_enter", False)
        desc = hk.get("description", "")
        comment = f"  ; {desc}" if desc else ""

        if v2:
            open_line = f"{trigger}:: {{{comment}"
            body.append(open_line)
            body += _body_v2(action_type, value, append_enter)
            body.append("}")
        else:
            body.append(f"{trigger}::{comment}")
            body += _body_v1(action_type, value, append_enter)
            body.append("return")

        body.append("")

    return "\n".join(header + body)


def _body_v1(action_type: str, value: str, append_enter: bool) -> list[str]:
    if action_type == "send_text":
        lines = [f"    SendRaw, {value}"]
        if append_enter:
            lines.append("    Send, {Enter}")
        return lines
    elif action_type == "run_command":
        return [f"    Run, {value}"]
    elif action_type == "always_on_top":
        return ["    Winset, Alwaysontop, , A"]
    elif action_type == "custom_ahk":
        return [f"    {line}" for line in value.splitlines()]
    return []


def _body_v2(action_type: str, value: str, append_enter: bool) -> list[str]:
    # Escape double-quotes inside value for v2 string literals
    escaped = value.replace('"', '""')
    if action_type == "send_text":
        lines = [f'    SendText "{escaped}"']
        if append_enter:
            lines.append('    Send "{Enter}"')
        return lines
    elif action_type == "run_command":
        return [f'    Run "{escaped}"']
    elif action_type == "always_on_top":
        return ['    WinSetAlwaysOnTop -1, "A"']
    elif action_type == "custom_ahk":
        return [f"    {line}" for line in value.splitlines()]
    return []
